---
title: 'Bios 6301: Assignment 4'
author: 'Haoyang Yi'
output: pdf_document
---

*Due Tuesday, 04 October, 1:00 PM*

**20/20 - Tianyi**

$5^{n=day}$ points taken off for each day late.

20 points total.

This assigment includes turning in the first three assignments. All three should
include knitr files (named `homework1.rmd`, `homework2.rmd`, `homework3.rmd`, `homework4.rmd`)
along with valid PDF output files. Inside each file, clearly indicate which
parts of your responses go with which problems (you may use the original homework
document as a template). Add your name as `author` to the file's metadata section.
Raw R code/output or word processor files are not acceptable.

Failure to properly name files or include author name may result in 5 points taken off.

### Question 1 ###

**10 points**

1. Use GitHub to turn in the first four homework assignments. Make sure the teacher (couthcommander) and TA (tinasunny2018) are collaborators. (5 points)

1. Commit each assignment individually.  This means your repository should have at least four commits. (5 points)

### Question 2 ###

**10 points**

Use \LaTeX to create the following expressions.

1. Hint: `\Rightarrow` (4 points)

$P(B)=\sum_{j}P(B|A_j)P(A_j)\\\Rightarrow P(A_i|B)=\frac{P(B|A_i)P(A_i)}{\sum_jP(B|A_j)P(A_j)}$
    

1. Hint: `\zeta` (3 points)


$\hat{f}(\zeta)=\int^\infty_{-\infty}f(x)e^{-2\pi ix\zeta}dx$


  

1. Hint: `\partial` (3 points)
$\mathbf{J}=\frac{d \mathbf{f}}{d \mathbf{x}}=\left[\frac{\partial \mathbf{f}}{\partial x_1} \ldots\frac{\partial \mathbf{f}}{\partial x_n}\right]=\left[\begin{array}{ccc}\frac{\partial f_1}{\partial x_1} & \cdots & \frac{\partial f_1}{\partial x_n} \\\vdots & \ddots & \vdots \\\frac{\partial f_m}{\partial x_1} & \cdots & \frac{\partial f_m}{\partial x_n}\end{array}\right]$
    